<?php

namespace app\modules\admin\models;

use Yii;
use yii\db\ActiveRecord;
use app\models\ImageUpload;

/**
 * This is the model class for table "categories".
 *
 * @property int $id
 * @property int $parent_id
 * @property string $name
 * @property string $img
 * @property string $description
 */
class Categories extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'],'required'],
            [['name', 'img'], 'string', 'max' => 255],
        ];
    }

//    public function getCategories(){
//        return $this->hasOne(Categories::className(),['id' => 'parent_id']);
//    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app','Категория(id)'),
            'name' => Yii::t('app','Название'),
            'img' => Yii::t('app', 'Картинка'),
        ];
    }

    public function saveImage($filename){
        $this->img = $filename;
        return $this->save(false);

    }

    public function getImage(){
        return ($this->img) ? '/images/categories/' . $this->img : '/no-image.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->img);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
