<?php

namespace app\modules\admin\models;

use Yii;
use yii\db\ActiveRecord;
use app\models\User;
use app\models\ImageUpload;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property int $category_id
 * @property string $name
 * @property int $price
 * @property string $img
 * @property string $description
 * @property int $user_id
 */
class Products extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'category_id', 'img'], 'required'],
            [['category_id', 'manufacturer_id', 'user_id'], 'integer'],
            [['eur'], 'number'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['img'], 'file', 'extensions'=>'jpg,png'],
        ];
    }

    public function getSubsection(){
        return $this->hasOne(Subsection::class,['id'=>'category_id']);
    }

    public function getUser(){
        return $this->hasOne(User::class,['id'=>'user_id']);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app','№'),
            'category_id' => Yii::t('app','Категория'),
            'manufacturer_id' => Yii::t('app', 'Производитель'),
            'name' => Yii::t('app','Название'),
            'eur' => Yii::t('app','Цена EUR'),
            'img' => Yii::t('app','Картинка'),
            'description' => Yii::t('app','Описание'),
            'user_id' => Yii::t('app','Пользователь'),
        ];
    }

    public function saveImage($filename){
        $this->img = $filename;
        return $this->save(false);

    }

    public function getImage(){
        return ($this->img) ? '/images/products/' . $this->img : '/no-image.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->img);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
